name: Linux Build Test

on: [push, pull_request]

jobs:
        
  Linux-LocalAI-Manager:
    runs-on: [ubuntu-latest]
    strategy:
      max-parallel: 5

    steps:
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install docker python-on-whales pyyaml PyInstaller requests py-cpuinfo nicegui openai colorama 
    - name: Download Files
      run: |
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/model_installer/model_installer.py
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/midori_program_ver.txt
        curl -O https://raw.githubusercontent.com/lunamidori5/Midori-AI/master/other_files/python_ver.py
    - name: Edit LocalAI Manager VER
      run: |
        python python_ver.py
        rm -f python_ver.py
    - name: Make EXE file
      run: |
        pyinstaller --onefile --clean model_installer.py